language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 7.1
    - 7.2

before_install:
    - go get -u github.com/stripe/stripe-mock
    - stripe-mock > /dev/null

install:
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - composer test
